apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260529-210306-pamimf246dpy-service
spec:
  selector:
    app: enterprise-system-20260529-210306-pamimf246dpy
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
